// Hand-authored mock data standing in for the Supabase tables (SRS.md §6).
// Shapes match the real schema 1:1 so lib/data/*.ts can swap its source without
// touching any component.

import type {
  AlumniProfile,
  BlogPost,
  Event,
  Member,
  Panel,
  Player,
  RegistrationSettings,
  SiteContent,
  Team,
} from "./types";

export const mockEvents: Event[] = [
  {
    id: "evt-1",
    name: "Inter-University Football Championship 2026",
    date: "2026-07-29",
    venue: "NSU Sports Complex",
    description:
      "Annual football championship featuring the best university teams across the country. Group stages are underway now, finals next week.",
    bannerImage: "/images/events/football.png",
    status: "Running",
  },
  {
    id: "evt-2",
    name: "Cricket Tournament 2026",
    date: "2026-08-25",
    venue: "NSU Cricket Ground",
    description: "Premier cricket tournament with teams from universities nationwide.",
    bannerImage: "/images/events/cricket.png",
    status: "Upcoming",
  },
  {
    id: "evt-3",
    name: "Annual Sports Excellence Awards",
    date: "2026-06-28",
    venue: "NSU Auditorium",
    description: "Celebrating outstanding athletic achievements and recognizing top performers from the season.",
    bannerImage: "/images/events/awards.png",
    status: "Finished",
  },
  {
    id: "evt-4",
    name: "Winter Swimming Championship",
    date: "2026-01-28",
    venue: "NSU Aquatic Center",
    description: "Competitive swimming event with multiple categories and age groups.",
    bannerImage: "/images/events/swimming.png",
    status: "Finished",
  },
];

export const mockTeams: Team[] = [
  {
    id: "team-1",
    name: "Football",
    description: "NSU SC's largest and most competitive squad.",
    bannerImage: "/images/teams/football.png",
    nickname: "Thunder Lions",
    achievement: "3x Champions 2023–2025",
  },
  {
    id: "team-2",
    name: "Cricket",
    description: "Home ground champions, two-time tournament winners.",
    bannerImage: "/images/teams/cricket.png",
    nickname: "Storm Strikers",
    achievement: "2x Tournament Winners",
  },
  {
    id: "team-3",
    name: "Handball",
    description: "Fast-growing team with a strong freshers pipeline.",
    bannerImage: null,
    nickname: "Iron Hawks",
    achievement: null,
  },
  {
    id: "team-4",
    name: "Basketball",
    description: "Undefeated 2025 season and still climbing.",
    bannerImage: "/images/teams/basketball.png",
    nickname: "Hoop Warriors",
    achievement: "Undefeated Season 2025",
  },
];

export const mockPlayers: Player[] = [
  // Football
  {
    id: "plyr-1",
    teamId: "team-1",
    name: "Ahmed Hassan",
    photo: null,
    email: "ahmed.hassan@nsusc.org",
    position: "Coach",
    bio: "Leading the squad since 2023, with three championship titles to date.",
    sortOrder: 1,
  },
  {
    id: "plyr-2",
    teamId: "team-1",
    name: "Rafiq Khan",
    photo: null,
    email: "rafiq.khan@nsusc.org",
    position: "Captain, Forward",
    bio: "Top scorer for two consecutive seasons and the team's on-field leader.",
    sortOrder: 2,
  },
  {
    id: "plyr-3",
    teamId: "team-1",
    name: "Imran Chowdhury",
    photo: null,
    email: "imran.chowdhury@nsusc.org",
    position: "Goalkeeper",
    bio: "Known for a wall of a save in last season's semifinal.",
    sortOrder: 3,
  },
  {
    id: "plyr-4",
    teamId: "team-1",
    name: "Nabil Islam",
    photo: null,
    email: "nabil.islam@nsusc.org",
    position: "Midfielder",
    bio: "Playmaker who controls the tempo of every match.",
    sortOrder: 4,
  },
  // Cricket
  {
    id: "plyr-5",
    teamId: "team-2",
    name: "Sabbir Rahman",
    photo: null,
    email: "sabbir.rahman@nsusc.org",
    position: "Coach",
    bio: "Former university-league all-rounder, coaching NSU SC since 2024.",
    sortOrder: 1,
  },
  {
    id: "plyr-6",
    teamId: "team-2",
    name: "Tamim Haque",
    photo: null,
    email: "tamim.haque@nsusc.org",
    position: "Captain, Batsman",
    bio: "Steady top-order batsman and calm presence under pressure.",
    sortOrder: 2,
  },
  {
    id: "plyr-7",
    teamId: "team-2",
    name: "Shakib Al Noman",
    photo: null,
    email: "shakib.alnoman@nsusc.org",
    position: "Bowler",
    bio: "Fast bowler with the best economy rate in last season's league.",
    sortOrder: 3,
  },
  // Handball
  {
    id: "plyr-8",
    teamId: "team-3",
    name: "Faisal Reza",
    photo: null,
    email: "faisal.reza@nsusc.org",
    position: "Captain",
    bio: "One of the founding members of the handball team.",
    sortOrder: 1,
  },
  {
    id: "plyr-9",
    teamId: "team-3",
    name: "Rakib Hasan",
    photo: null,
    email: "rakib.hasan@nsusc.org",
    position: "Left Wing",
    bio: "Quick on the counter-attack and a reliable finisher.",
    sortOrder: 2,
  },
  // Basketball
  {
    id: "plyr-10",
    teamId: "team-4",
    name: "James Wilson",
    photo: null,
    email: "james.wilson@nsusc.org",
    position: "Coach",
    bio: "Guided the team to an undefeated 2025 season.",
    sortOrder: 1,
  },
  {
    id: "plyr-11",
    teamId: "team-4",
    name: "Rahim Ahmed",
    photo: null,
    email: "rahim.ahmed@nsusc.org",
    position: "Captain, Point Guard",
    bio: "Floor general with a knack for clutch shots.",
    sortOrder: 2,
  },
  {
    id: "plyr-12",
    teamId: "team-4",
    name: "Zayn Karim",
    photo: null,
    email: "zayn.karim@nsusc.org",
    position: "Center",
    bio: "Dominant under the basket on both ends of the court.",
    sortOrder: 3,
  },
];

export const mockPanel: Panel = { id: "panel-2025-26", name: "Panel 2025-26", isActive: true };

export const mockMembers: Member[] = [
  {
    id: "mem-1",
    panelId: "panel-2025-26",
    name: "Ariana Rahman",
    photo: null,
    designation: "President",
    tier: "Executive",
    email: "ariana.rahman@nsusc.org",
    phone: "+880 1711-000001",
    additionalInfo: null,
    sortOrder: 1,
  },
  {
    id: "mem-2",
    panelId: "panel-2025-26",
    name: "Tanvir Ahmed",
    photo: null,
    designation: "General Secretary",
    tier: "Executive",
    email: "tanvir.ahmed@nsusc.org",
    phone: "+880 1711-000002",
    additionalInfo: null,
    sortOrder: 2,
  },
  {
    id: "mem-3",
    panelId: "panel-2025-26",
    name: "Farhan Kabir",
    photo: null,
    designation: "Sports Secretary",
    tier: "Sub-Executive",
    email: "farhan.kabir@nsusc.org",
    phone: "+880 1711-000003",
    additionalInfo: null,
    sortOrder: 1,
  },
];

export const mockRegistrationSettings: RegistrationSettings = {
  isOpen: true,
  googleFormUrl: "https://forms.google.com/nsusc-membership",
  nextIntakeDate: null,
};

export const mockSiteContent: SiteContent[] = [
  {
    pageKey: "home_tagline",
    content: "One club, every sport — compete, connect, and represent NSU.",
    featuredEventId: null,
  },
  {
    pageKey: "home_featured_event",
    content: "",
    featuredEventId: "evt-1",
  },
];

export const mockAlumni: AlumniProfile[] = [
  {
    id: "alum-1",
    name: "Tahsin Rahman",
    photo: null,
    graduationYear: 2023,
    team: "Football",
    currentRole: "Software Engineer at Therap BD",
    quote: "NSU SC taught me as much about teamwork as any classroom did.",
  },
  {
    id: "alum-2",
    name: "Nusrat Jahan",
    photo: null,
    graduationYear: 2022,
    team: "Cricket",
    currentRole: "Business Analyst at bKash",
    quote: "The friendships I made on the pitch are still my closest ones today.",
  },
  {
    id: "alum-3",
    name: "Omar Faruk",
    photo: null,
    graduationYear: 2021,
    team: "Basketball",
    currentRole: "Product Manager at Pathao",
    quote: null,
  },
  {
    id: "alum-4",
    name: "Mahin Chowdhury",
    photo: null,
    graduationYear: 2024,
    team: "Handball",
    currentRole: "Graduate Student, University of British Columbia",
    quote: "Being team captain shaped how I lead teams today.",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "post-1",
    title: "Thunder Lions Clinch Third Straight Championship",
    excerpt: "A dramatic penalty shootout capped off an unbeaten campaign for the football squad.",
    category: "Football",
    coverImage: "/images/teams/football.png",
    author: "NSU SC Media",
    date: "2026-06-30",
    readTimeMinutes: 4,
  },
  {
    id: "post-2",
    title: "Inside the Cricket Tournament 2026 Build-Up",
    excerpt: "Storm Strikers' captain shares how the squad is preparing for next month's tournament.",
    category: "Cricket",
    coverImage: "/images/teams/cricket.png",
    author: "Tamim Haque",
    date: "2026-07-10",
    readTimeMinutes: 3,
  },
  {
    id: "post-3",
    title: "Player Spotlight: Rahim Ahmed",
    excerpt: "From walk-on to captain — the Hoop Warriors' floor general on leadership and clutch shots.",
    category: "Profiles",
    coverImage: "/images/teams/basketball.png",
    author: "NSU SC Media",
    date: "2026-06-15",
    readTimeMinutes: 5,
  },
  {
    id: "post-4",
    title: "Recap: Annual Sports Excellence Awards",
    excerpt: "Celebrating the athletes and volunteers who defined this season.",
    category: "Events",
    coverImage: "/images/events/awards.png",
    author: "NSU SC Media",
    date: "2026-06-29",
    readTimeMinutes: 3,
  },
];
